#!/usr/bin/python

"""
Demo exe that reads in an fname and log entry from stdin and writes
the fname and author name, pipe separated, to stdout.
"""

import sys

(fname, commit, author_name, author_email,
 log_msg, diff, raw_log) = sys.stdin.read().split('\0')

print "%s|%s" % (fname, author_name)
